### ISSUE TITLE
fatal error: 'sycl/ext/intel/fpga_extensions.hpp' file not found

### ISSUE THREAD

**Issue by tcovert2015** [oneapi-src/oneAPI-samples#656]
# Summary
I am attempting to complete some of the tutorials and reference designs. Each time I run Make in the instructions it gives the following error.

```
[ 25%] Building CXX object src/CMakeFiles/fpga_reg.fpga.dir/fpga_reg.cpp.o
/home/u86836/oneAPI-samples/DirectProgramming/DPC++FPGA/Tutorials/Features/fpga_reg/src/fpga_reg.cpp:7:10: fatal error: 'sycl/ext/intel/fpga_extensions.hpp' file not found
#include <sycl/ext/intel/fpga_extensions.hpp>
```
I am running on just the standard OneAPI login node on the DevCloud

# Version
Not Sure

# Environment
Ubuntu 20 LTS for host machine to ssh to the devcloud

# Steps to reproduce
Just follow any of the Reference Designs or Tutorials. The error appears when I use the Make command. I have tried multiple reference designs and tutorials.

Specifically the DPC++FPGA/Tutorials/Features/fpga_reg, DPC++FPGA/ReferenceDesigns/mvdr_beamforming and DPC++FPGA/ReferenceDesigns/crr

# Observed behavior
Error when using Make
```
[ 25%] Building CXX object src/CMakeFiles/fpga_reg.fpga.dir/fpga_reg.cpp.o
/home/u86836/oneAPI-samples/DirectProgramming/DPC++FPGA/Tutorials/Features/fpga_reg/src/fpga_reg.cpp:7:10: fatal error: 'sycl/ext/intel/fpga_extensions.hpp' file not found
#include <sycl/ext/intel/fpga_extensions.hpp>
```
# Expected behavior
Make to complete without error.

**Comment by mdbtucker** [comment]
The Code Samples use labels to mark versions.  You are attempting to use the tip of the master branch (which includes changes for the unreleased 2021.4 version) with the 2021.3 release of the compiler.  

This page https://github.com/oneapi-src/oneAPI-samples/tags shows the available tags.  You should checkout the 2021.3.0 tag to compile with the 2021.3 compiler.
